# Generated by Django 4.2.3 on 2023-08-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rclonetransfer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_credentials',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dropbox_token',
            field=models.TextField(blank=True),
        ),
    ]
