# Generated by Django 4.2.3 on 2023-08-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rclonetransfer', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dropbox_token',
            field=models.TextField(blank=True, db_column='dropbox_token'),
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dropbox_token',
            new_name='_dropbox_token',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_token',
            field=models.TextField(blank=True, db_column='google_token'),
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='google_token',
            new_name='_google_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dropbox_refresh_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='google_refresh_token',
        ),
    ]
